### ISSUE TITLE
pioneチュートリアルのテストプログラムが正常終了しません

### ISSUE THREAD

**Issue by takahiro-pione** [pione/pione#70]
基本１は、outputファイルはできますが、プログラムが終了せず、プロンプトが戻ってきません。

基本２と３は、以下のワーニングが出て、プログラムが終了しません。
warn: cannot move /var/folders/z5/nt6x76t92sv04m1cs7338bjw0000gt/T/pione/takahiro/working_e9674d23-c758-4b67-9ec8-984ff4161507/test.in to #<Pione::Location::LocalLocation local:/Users/takahiro/Documents/PIONE_Tutorial/MultiplyingOutput/.Anonymous/Main/e9bae3c0185d4d54767a586a83acffd7/test.in>: same file: /var/folders/z5/nt6x76t92sv04m1cs7338bjw0000gt/T/pione/takahiro/working_e9674d23-c758-4b67-9ec8-984ff4161507/test.in and /Users/takahiro/Documents/PIONE_Tutorial/MultiplyingOutput/.Anonymous/Main/e9bae3c0185d4d54767a586a83acffd7/test.in [/Library/Ruby/Gems/2.0.0/gems/pione-0.5.0/lib/pione/rule-engine/action-handler.rb:119:in `rescue in block in write_other_resources'](2016-03-07T10:32:25.767+09:00, #21497)

基本４は、以下のようなエラーが出て、プログラムが実行できず、終了します。
info ERROR: Expected one of [EXPR_OPERATOR_APPLICATION, REVERSE_MESSAGE_SENDING, EXPR_ELEMENT] at line 1 char 1.
/Library/Ruby/Gems/2.0.0/gems/pione-0.5.0/lib/pione/tuple-space/basic-tuple.rb:292:in `from_array': can't convert DRb::DRbObject to Array (DRb::DRbObject#to_a gives DRb::DRbObject) (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/pione-0.5.0/lib/pione/tuple-space/tuple-space-server.rb:28:in`block in module:TupleSpaceServerMethod'
    from /Library/Ruby/Gems/2.0.0/gems/pione-0.5.0/lib/pione/tuple-space/tuple-space-server.rb:19:in `call'

作業環境は、
OS X Yosemite10.10.5
ruby 2.0.0p481
gem 2.0.14
pione 0.5.0
です。
何が問題でしょうか？

**Comment by keita** [comment]
ご報告誠にありがとうございました。
基本1は停止処理が機能しなかった結果と思われます。
基本２と3の警告はファイル移動時に衝突が発生した事によります。
基本4についてはPIONE式の解析エラーのように見えます。

原因を調査したいのですが、週末まで時間がとれないので少々お待ち頂けますでしょうか。

**Comment by takahiro-pione** [comment]
お忙しい中、お返事、ありがとうございます。
PIONEを使い始めたばかりで、何が起こっているのかわからず、困っていました。
原因調査いただけると、大変助かります。
どうぞ、よろしくお願いします。

**Comment by takahiro-pione** [comment]
Rubyのバージョンを1.9.3にしたところ、動くようになりました。
1.9.3より上のバージョンでは、動かないということでしょうか？
どのバージョンで動くのか、なにか情報があれば、お教えください。
よろしくお願いします。

**Comment by keita** [comment]
PIONEは2.0以上の場合、排他制御の仕様変更の為に動作に問題があります。
おそらくこれが基本1,2,3の原因だろうと思われます。
ただし、基本4についてはちょっと別ではないかと考えています。

上記の確認は週末に行います。
また、さすがに2.0系で動かないのはそろそろ問題ですので、
2.0系で動作するように変更できるかは調べてみるつもりです。

**Comment by takahiro-pione** [comment]
お返事、ありがとうございます。
基本4に関しては私のミスで、pioneファイルにバグがあったために起こっていました。
申し訳ありません。

現在、プログラムは終了して、プロンプトが戻って来るようにはなりましたが、
基本2以降、ワーニングが出ていて、そのためにか、結果の出力が不安定な結果となっています。
このことに関して、次のIssueにアップしますので、ご対応のほど、よろしくお願いします。

**Comment by keita** [comment]
調査の結果ですが、2.0系で動くようにするのはそれなりに時間がかかりそうですので、申し訳ありませんがもう少々1.9系列でお願いします。

警告については、ルール発火タイミング制御がうまくいっていない事が根本原因のファイル衝突によるものなのですが、こちらも対処が難しいので解決まで時間を頂きます。
